package com.ayadyasmine.pharmacyecom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PromotionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromotionAllPropertiesEquals(Promotion expected, Promotion actual) {
        assertPromotionAutoGeneratedPropertiesEquals(expected, actual);
        assertPromotionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromotionAllUpdatablePropertiesEquals(Promotion expected, Promotion actual) {
        assertPromotionUpdatableFieldsEquals(expected, actual);
        assertPromotionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromotionAutoGeneratedPropertiesEquals(Promotion expected, Promotion actual) {
        assertThat(actual)
            .as("Verify Promotion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromotionUpdatableFieldsEquals(Promotion expected, Promotion actual) {
        assertThat(actual)
            .as("Verify Promotion relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDiscountPercent()).as("check discountPercent").isEqualTo(expected.getDiscountPercent()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromotionUpdatableRelationshipsEquals(Promotion expected, Promotion actual) {
        assertThat(actual)
            .as("Verify Promotion relationships")
            .satisfies(a -> assertThat(a.getProducts()).as("check products").isEqualTo(expected.getProducts()));
    }
}
